##############################################################################################
#
# Travis CI configuration file
# 
# Set the required secrets in the build settings of the project:
#   - BINTRAY_USER
#   - BINTRAY_API_KEY
#
##############################################################################################
os: linux
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - fakeroot
    - python-flake8

language: node_js
node_js:
  - "6"

cache:
  directories:
    - $HOME/.npm

env:
  global:
  - PACKAGE_NAME=server-dashboard
  - PACKAGE_DESC="Server Dashboard displayin resources usage"
  - PACKAGE_AUTHOR=geld.tech
  - BINTRAY_REPO_NAME=debian
  - BINTRAY_LICENSE=Apache-2.0
  - BINTRAY_DESCRIPTOR=bintray-descriptor.json.in

before_install:
  # Export variables containing versions and filename
  - export PACKAGE_DIR=/opt/geld/webapps/$PACKAGE_NAME
  - export RELEASE_VERSION=$(cat VERSION)
  - export BUILD_VERSION=$RELEASE_VERSION.$TRAVIS_BUILD_NUMBER
  - export BUILD_DATE=$(date "+%Y%m%d")
  - export PACKAGE_VERSION=$PACKAGE_NAME-$BUILD_VERSION
  - export PACKAGE_VERSION_DEB=$PACKAGE_VERSION.deb
  # Replace version and build number with the Debian control file
  - find . -type f | xargs sed -i "s/__PACKAGE_NAME__/$PACKAGE_NAME/g"
  - find . -type f | xargs sed -i "s/__PACKAGE_DESC__/$PACKAGE_DESC/g"
  - find . -type f | xargs sed -i "s/__VERSION__/$BUILD_VERSION/g"
  - find . -type f | xargs sed -i "s/__USER__/$BINTRAY_USER/g"
  - find . -type f | xargs sed -i "s/__DATE__/$BUILD_DATE/g"
  - find . -type f | xargs sed -i "s/__GA_UA_ID__/$GA_UA_ID/g"
  - find . -type f | xargs sed -i "s.__PACKAGE_DIR__.$PACKAGE_DIR.g"

install:
  # NPM packages
  - npm update -g npm
  # Build Vue web application
  - cd sources/webapp/
  - npm install
  - npm run lint
  - npm audit
  - npm run build
  - cd ../..
  # Flask application
  - cd sources/server/
  # Enforce no syntax errors or undefined names
  - flake8 . --exclude=dependencies --ignore=E501 --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # Displays other potential issues with coding style as warnings only
  - flake8 . --exclude=dependencies --ignore=E501 --count --exit-zero --max-complexity=10 --statistics
  - cd ../..

before_script:
  # Create the package directories structure
  - mkdir $PACKAGE_VERSION
  - mkdir -p $PACKAGE_VERSION/$PACKAGE_DIR/templates/
  - mkdir -p $PACKAGE_VERSION/$PACKAGE_DIR/static/
  - mkdir -p $PACKAGE_VERSION/DEBIAN/
  # Layout the files in the directories structure
  - rsync -a --chown=root:www-data sources/files/ $PACKAGE_VERSION/
  - rsync -a --chown=root:www-data sources/server/ $PACKAGE_VERSION/$PACKAGE_DIR
  - rsync -a --chown=root:www-data sources/webapp/dist/*.html $PACKAGE_VERSION/$PACKAGE_DIR/templates/
  - rsync -a -r --chown=root:www-data sources/webapp/dist/static/ $PACKAGE_VERSION/$PACKAGE_DIR/static/
  - rsync -a -r --chown=root:www-data packages/DEBIAN/ $PACKAGE_VERSION/DEBIAN/
  # Output files and directories for debugging purpose
  - ls -lsthRA $PACKAGE_VERSION/

script:
  # Create the Debian package using fakeroot forcing ownership to root user
  - fakeroot dpkg-deb --build $PACKAGE_VERSION

after_success:
  # Stores hashes of created package to ensure upload successful
  - export LOCAL_SHA256=$( sha256sum $PACKAGE_VERSION_DEB | cut -d " " -f1 )
  - 'echo "LOCAL_SHA256=$LOCAL_SHA256"'
  # Output detail on the resulting package for debugging purpose
  - ls -l $PACKAGE_VERSION
  - dpkg --contents $PACKAGE_VERSION_DEB
  - md5sum $PACKAGE_VERSION_DEB
  - sha256sum $PACKAGE_VERSION_DEB

before_deploy:
  # Set the packages name and details in the descriptor file
  - sed -i "s/__NAME__/$PACKAGE_NAME/g" $BINTRAY_DESCRIPTOR
  - sed -i "s/__PACKAGE_DESC__/$PACKAGE_DESC/g" $BINTRAY_DESCRIPTOR
  - sed -i "s/__PACKAGE_AUTHOR__/$PACKAGE_AUTHOR/g" $BINTRAY_DESCRIPTOR
  - sed -i "s/__REPO_NAME__/$BINTRAY_REPO_NAME/g" $BINTRAY_DESCRIPTOR
  - sed -i "s/__SUBJECT__/$BINTRAY_SUBJECT/g" $BINTRAY_DESCRIPTOR
  - sed -i "s/__LICENSE__/$BINTRAY_LICENSE/g" $BINTRAY_DESCRIPTOR
  - sed -i "s/__VERSION__/$BUILD_VERSION/g" $BINTRAY_DESCRIPTOR

deploy:
  # Upload debian packages to Bintray
  provider: bintray
  file: $BINTRAY_DESCRIPTOR
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  skip_cleanup: true

after_deploy:
  # Retrieve releases list and delete old packages files
  - sleep 60
  - 'export OLD_RELEASES=$(curl -L -v --silent https://bintray.com/$BINTRAY_SUBJECT/$BINTRAY_REPO_NAME/download_file?file_path=Packages.gz | zcat | grep -A 6 "Package: $PACKAGE_NAME" | grep Version | cut -d" " -f2 | sort -V | head -n -5)'
  - 'echo "OLD_RELEASES: $OLD_RELEASES"'
  - >
    for RELEASE_NUM in $OLD_RELEASES; do
      echo "Sending API request to delete $PACKAGE_NAME version $RELEASE_NUM" ;
      curl --silent --show-error --fail -X DELETE -u$BINTRAY_USER:$BINTRAY_API_KEY https://api.bintray.com/content/$BINTRAY_SUBJECT/$BINTRAY_REPO_NAME/$PACKAGE_NAME-$RELEASE_NUM.deb ;
      curl --silent --show-error --fail -X DELETE -u$BINTRAY_USER:$BINTRAY_API_KEY https://api.bintray.com/content/$BINTRAY_SUBJECT/$BINTRAY_REPO_NAME/$PACKAGE_NAME-$RELEASE_NUM.deb.asc ;
      sleep 5 ;
    done
  
  # Add time delay to let the servers process the uploaded new version and delete old files
  - sleep 120
  
  # Retrieve SHA256 sum and compare with local sum to ensure correct file uploaded
  # (Useful to detect upload issues or problems with Bintray)
  - export REMOTE_SHA256=$(curl -L -v --silent https://bintray.com/$BINTRAY_SUBJECT/$BINTRAY_REPO_NAME/download_file?file_path=Packages.gz | zcat | grep -A 3 $PACKAGE_VERSION_DEB | grep SHA256 | cut -d" " -f2)
  - 'echo "REMOTE_SHA256: $REMOTE_SHA256"'
  - >
    if [[ "$LOCAL_SHA256" != "$REMOTE_SHA256" ]]; then
      echo "SHA256 sums don't match: $LOCAL_SHA256 vs $REMOTE_SHA256";
      travis_terminate 1;
    fi

  # Place link to the file in download list
  - >
    curl --silent --show-error --fail -X PUT -H "Content-Type: application/json" -d'{"list_in_downloads": true}' -u$BINTRAY_USER:$BINTRAY_API_KEY https://api.bintray.com/file_metadata/$BINTRAY_SUBJECT/$BINTRAY_REPO_NAME/$PACKAGE_VERSION_DEB
